=== PhilipHerweling24/Enterprise-Infrastructure/Lab2/invoice.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.tudublin.ie"
xmlns="http://www. tudublin.ie"
elementFormDefault="qualified">

<xs:element name="invoice">
  <xs:complexType>
    <xs:sequence>
	
    <xs:element name="invoicedate" type="xs:string"/>
	  <xs:element name="invoicetotal" type="xs:decimal"/>
	  <xs:element name="issuedby" type="xs:string"/>
	  
	  <xs:element name="billto">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
	  </xs:element>
	  
	  <xs:element name="item" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="quantity" type="xs:positiveInteger"/>
            <xs:element name="price" type="xs:decimal"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
	  
	  <xs:element name="paymentinfo">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="accounttype" type="xs:string"/>
            <xs:element name="iban" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
	  </xs:element>
	  
    </xs:sequence>
	<xs:attribute name="invoiceno" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>

</xs:schema>

=== PhilipHerweling24/Enterprise-Infrastructure/Lab2/invoice.xml
<?xml version="1.0"?>
<invoice invoiceno="100"
xmlns="http://www.tudublin.ie"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.tudublin.ie invoice.xsd">

  <invoicedate>12/02/2022</invoicedate>
  <invoicetotal>110.50</invoicetotal>
  <issuedby>Clothes Wholesaler</issuedby>
  <billto>
    <name>Philip Herweling</name>
    <address>Morette Emo</address>
    <city>Laois</city>
  </billto>
  <item>
    <title>Nicce Jumper</title>
    <quantity>1</quantity>
    <price>65.50</price>
  </item>
  <item>
    <title>United Halfzip</title>
    <quantity>1</quantity>
    <price>45.00</price>
  </item>
  <paymentinfo>
	<accounttype>Current</accounttype>
	<iban>UL200023030</iban>
  </paymentinfo>
</invoice>
